### ISSUE TITLE
Enlace a informe caído

### ISSUE THREAD

**Issue by lucasp90** [HacKanCuBa/informe-votar#2]
Hoy he intentado leer el [primer artículo recomendado](http://www.vialibre.org.ar/2015/06/24/el-sistema-de-voto-electronico-en-la-ciudad-de-buenos-aires-una-solucionen-busca-de-problemas) y no he podido acceder a él. Al parecer está caído.

**Comment by HacKanCuBa** [comment]
Gracias por el aviso! Habrá sido temporal, ya lo veo arriba.
Por si acaso, dejo un enlace a [archive.org](http://web.archive.org/web/20160611072701/http://www.vialibre.org.ar/2015/06/24/el-sistema-de-voto-electronico-en-la-ciudad-de-buenos-aires-una-solucionen-busca-de-problemas/).

Integridad: `sha256(VE.CdBuenosAires.Parte1_.pdf)=2453ba3964f166cdf41372cc0480df20d6fb1ff7a1c9c627733db26b4ce65800`
